# Generated by Django 5.1.2 on 2024-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "activities",
            "0002_attivita_alter_booking_status_alter_booking_activity_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="attivita",
            old_name="titolo",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="attivita",
            name="data_fine",
        ),
        migrations.RemoveField(
            model_name="attivita",
            name="data_inizio",
        ),
        migrations.AddField(
            model_name="attivita",
            name="costo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="attivita",
            name="posti_massimi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attivita",
            name="tipo",
            field=models.CharField(
                choices=[("EDU", "Educativa"), ("DOM", "Domenicale"), ("ALT", "Altro")],
                max_length=3,
            ),
        ),
    ]
