# Generated by Django 5.1.2 on 2024-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestione", "0003_alter_attivita_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attivita",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DID", "Didattica"),
                    ("LAB", "Laboratori/Visite domenicali "),
                    ("ALT", "Feste ed Eventi"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="prenotazione",
            name="status",
            field=models.CharField(
                choices=[
                    ("CON", "Confermata"),
                    ("ATT", "In Attesa"),
                    ("CAN", "Cancellata"),
                ],
                default="ATT",
                max_length=10,
            ),
        ),
    ]
