# Generated by Django 5.1.2 on 2024-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestione", "0004_alter_attivita_tipo_alter_prenotazione_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="prenotazione",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prenotazione",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prenotazione",
            name="status",
            field=models.CharField(
                choices=[
                    ("CON", "Confermata"),
                    ("ATT", "In Attesa"),
                    ("CAN", "Cancellata"),
                ],
                default="ATT",
                max_length=50,
            ),
        ),
    ]
