# Generated by Django 5.1.2 on 2024-11-11 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestione", "0005_prenotazione_created_at_prenotazione_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prenotazione",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
