# Generated by Django 5.1.2 on 2024-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestione", "0007_remove_prenotazione_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disponibilita",
            name="posti_disponibili",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
